import turtle
meow = turtle.Pen()
racer = turtle.Pen()
racer.up()
racer.backward(50)
racer.left(90)
racer.forward(20)
racer.right(90)
racer.forward(40)
racer.down()
racer.color(1,0,0)
meow.color(0.139,0.69,0.19)
print("Meow, your enemy is faster! I'll make him go behind you to make sure you have a chance.")
meow.forward(310) 
racer.forward(310)
print("Meow wins!")
